In [269]:
import numpy as np
import os,sys,inspect
import importlib
%pdb on

# (1) find the path
dirpath = os.getcwd()
i = 0
while(os.path.basename(dirpath) != "IEMS450_HW") and i <10:
    dirpath = os.path.dirname(dirpath) 
    i = i + 1
targetdir = dirpath + '/HW5/functions'
if targetdir not in sys.path:
    sys.path.insert(0,targetdir)

import solve as solve
importlib.reload(solve)

Automatic pdb calling has been turned ON


<module 'solve' from '/Users/jingyuanwang/GitHub/IEMS450_HW/HW5/functions/solve.py'>

In [270]:
f = solve.obj_function()
c = solve.constraints()
x_true = np.array(  [-1.71, 1.59, 1.82, -0.763, -0.763] )

model = solve.SQP(f,c)

In [271]:
x0       = np.array(  [-1.8, 1.7, 1.9, -0.8, -0.8] )
lambda_0 = np.ones((3,))
x        = model.run(x0, lambda_0)
print(x)

[-1.70800095  1.60119498  1.82951925 -0.76543021 -0.76543021]


In [272]:
x0       = x0 + 0.1
x       = model.run(x0, lambda_0)
print(x)

[-1.64742036  1.63908144  1.84171871 -0.77701057 -0.77701057]


In [274]:
print(x_true)

[-1.71   1.59   1.82  -0.763 -0.763]
